branches:
  only:
  - master

language: groovy

jdk:
  - oraclejdk8
  - openjdk8

addons:
  apt:
    packages:
    - sox
    - speech-tools

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
