name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v2

      # https://github.com/actions/setup-java
      - uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: '8'

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y sox speech-tools

      - name: Build with Gradle
        run: ./gradlew build
